### ISSUE TITLE
Add check for listed command when remove.

### ISSUE THREAD

**Issue by TheUserDead** [Darrionat/Command-Cooldown#2]
Hello. Found a possible bug. 
When i don't understand correctly how remove command from cooldown. 
Plugin allow me to use empty command and i receive recursion where i can't go out from configuration mode even i type /cc cancel
It's made me use console to disable plugin.

Log:
`[21:03:15] [Server thread/INFO]: UserD issued server command: /cc remove back
[21:03:22] [Server thread/INFO]: UserD issued server command: /back
[21:03:26] [Server thread/INFO]: UserD issued server command: /cc remove back
[21:03:33] [Server thread/INFO]: UserD issued server command: /back
[21:03:40] [Server thread/INFO]: UserD issued server command: /cc list
[21:03:49] [Server thread/INFO]: UserD issued server command: /cc remove
[21:03:57] [Server thread/INFO]: UserD issued server command: /cc remove
[21:04:03] [Server thread/INFO]: UserD issued server command: /back
[21:04:09] [Server thread/INFO]: UserD issued server command: /cc remove
[21:04:14] [Server thread/INFO]: UserD issued server command: /back
[21:04:21] [Server thread/INFO]: UserD issued server command: /cc list
>cc reload
[21:05:21] [Server thread/INFO]: COMMAND COOLDOWN v2.0 BETA-2
[21:05:21] [Server thread/INFO]:   Author: Darrionat
[21:05:21] [Server thread/INFO]:   Support: https://discord.gg/xNKrH5Z
[21:05:21] [Server thread/INFO]:   /cc help - For additional information
[21:05:31] [Server thread/INFO]: UserD issued server command: /cc reload
[21:05:35] [Server thread/INFO]: UserD issued server command: /cc list
[21:06:02] [Server thread/INFO]: UserD issued server command: /cc cancel
[21:06:04] [Async Chat Thread - #24/ERROR]: Could not pass event AsyncPlayerChatEvent to CommandCooldown v2.0 BETA-2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) [spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
        at net.minecraft.server.v1_16_R2.PlayerConnection.chat(PlayerConnection.java:1619) [spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1557) [spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NullPointerException
        at me.Darrionat.CommandCooldown.editors.RemoveCommandEditor.onArgumentsMessage(RemoveCommandEditor.java:98) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor245.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
        ... 11 more
[21:06:08] [Async Chat Thread - #24/ERROR]: Could not pass event AsyncPlayerChatEvent to CommandCooldown v2.0 BETA-2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) [spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
        at net.minecraft.server.v1_16_R2.PlayerConnection.chat(PlayerConnection.java:1619) [spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1557) [spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
`

**Comment by Darrionat** [comment]
Outdated issue. This has been patched in newer versions. Sorry for the late response, I never saw this.
